  - Home: index.md
  - About Us: about.md
  - Services: services/index.md
  - Projects: projects/index.md
  - Contact: contact.md

extra_css:
  - extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/AgamConstruction

copyright: Copyright &copy; 2026 Agam Construction